<#
.SYNOPSIS
  Drives sustained traffic against the lab webapp's intentionally-inefficient
  endpoint so that Application Insights Code Optimizations (Profiler-based)
  surfaces recommendations like "Use StringBuilder", "Excessive exceptions"
  and "Sync over async".

.DESCRIPTION
  Code Optimizations are generated by the Profiler back-end after it ingests
  enough trace samples that contain a detectable anti-pattern. To make that
  happen quickly in a lab you need:

    1. Profiler enabled on the App Service              (already wired in
       infra/modules/appservice.bicep)
    2. The app code to contain the anti-pattern         (added as
       /api/inefficient in workloads/webapp/Program.cs)
    3. Sustained traffic that hits that endpoint        (this script)

  This script:
    * Looks up the lab webapp from the resource group.
    * (Optional) Republishes the webapp so the new /api/inefficient endpoint
      is live. Skip with -SkipPublish if you already published it.
    * Pings /api/inefficient + a few support endpoints with N parallel
      workers for -DurationMinutes minutes.
    * Prints a follow-up checklist with where to find the recommendation in
      the portal.

.PARAMETER ResourceGroup
  The lab resource group. Defaults to 'rg-azure-monitor-lab'.

.PARAMETER DurationMinutes
  How long to drive load. Defaults to 30 minutes. The Code Optimizations
  service typically needs 1-24 h of traces before a recommendation appears,
  so feel free to leave it running longer (or rerun later).

.PARAMETER Concurrency
  Number of parallel callers. Defaults to 8.

.PARAMETER SkipPublish
  Skip rebuilding/zipping/deploying the webapp. Use this once you have
  already published the new endpoint at least once.

.EXAMPLE
  ./scripts/trigger-code-optimization.ps1

.EXAMPLE
  ./scripts/trigger-code-optimization.ps1 -DurationMinutes 60 -Concurrency 12

.EXAMPLE
  ./scripts/trigger-code-optimization.ps1 -SkipPublish -DurationMinutes 15
#>
[CmdletBinding()]
param(
  [string] $ResourceGroup   = 'rg-azure-monitor-lab',
  [int]    $DurationMinutes = 30,
  [int]    $Concurrency     = 8,
  [switch] $SkipPublish
)

$ErrorActionPreference = 'Stop'
function Write-Step($msg) { Write-Host "`n==> $msg" -ForegroundColor Cyan }
function Write-Info($msg) { Write-Host "    $msg" -ForegroundColor DarkGray }

# --- Subscription guardrail ----------------------------------------------------
$targetFile = Join-Path $PSScriptRoot '..' '.azure-target.json'
if (Test-Path $targetFile) {
  $target = Get-Content -Raw $targetFile | ConvertFrom-Json
  az account set --subscription $target.expectedSubscriptionId | Out-Null
  $active = az account show --query "{id:id, tenantId:tenantId}" -o json | ConvertFrom-Json
  if ($active.id -ne $target.expectedSubscriptionId -or $active.tenantId -ne $target.expectedTenantId) {
    throw "BLOCKED: not on allowed lab subscription ($($target.expectedSubscriptionId)). Aborting."
  }
  Write-Info "Subscription guardrail OK ($($active.id))."
}

# --- Resolve webapp ------------------------------------------------------------
Write-Step "Resolving lab webapp in $ResourceGroup"
$webAppName = az webapp list -g $ResourceGroup --query "[0].name" -o tsv
if ([string]::IsNullOrWhiteSpace($webAppName)) {
  throw "No App Service found in resource group '$ResourceGroup'."
}
$webAppHost = az webapp show -g $ResourceGroup -n $webAppName --query defaultHostName -o tsv
$baseUrl    = "https://$webAppHost"
Write-Info "WebApp : $webAppName"
Write-Info "Host   : $webAppHost"

# --- Publish updated webapp (unless skipped) -----------------------------------
if (-not $SkipPublish) {
  Write-Step "Publishing AmlabHello so /api/inefficient is live"
  $pub    = Join-Path $env:TEMP "amlab-pub-$([guid]::NewGuid().ToString('N'))"
  $csproj = Join-Path $PSScriptRoot '..' 'workloads' 'webapp' 'AmlabHello.csproj'
  dotnet publish $csproj -c Release -o $pub --nologo --verbosity quiet | Out-Null
  $zip = "$pub.zip"
  Compress-Archive -Path "$pub\*" -DestinationPath $zip -Force
  az webapp deploy `
    --resource-group $ResourceGroup --name $webAppName `
    --src-path $zip --type zip --restart true --output none
  Remove-Item -Recurse -Force $pub
  Remove-Item -Force $zip
  Write-Info "Publish complete; waiting 20s for cold-start."
  Start-Sleep -Seconds 20
} else {
  Write-Info "Skipping publish (per -SkipPublish)."
}

# --- Verify the endpoint exists ------------------------------------------------
Write-Step "Verifying /api/inefficient is reachable"
try {
  $probe = Invoke-WebRequest -Uri "$baseUrl/api/inefficient" -UseBasicParsing -TimeoutSec 60
  Write-Info "Probe status: $($probe.StatusCode)  (body length $($probe.Content.Length))"
} catch {
  throw "Probe to $baseUrl/api/inefficient failed: $($_.Exception.Message). Did you publish? Re-run without -SkipPublish."
}

# --- Drive sustained load ------------------------------------------------------
Write-Step "Driving load: $Concurrency workers x $DurationMinutes min"
Write-Info "Target endpoints: /api/inefficient (90%) + /api/slow (5%) + /api/explode (5%)"

$endAt = (Get-Date).AddMinutes($DurationMinutes)
$jobs  = @()

for ($w = 1; $w -le $Concurrency; $w++) {
  $jobs += Start-Job -Name "amlab-codeopt-$w" -ScriptBlock {
    param($base, $deadline, $workerId)
    $count = 0
    $errs  = 0
    while ((Get-Date) -lt $deadline) {
      $r = Get-Random -Minimum 0 -Maximum 100
      $path = if    ($r -lt 90) { '/api/inefficient' }
              elseif ($r -lt 95) { '/api/slow' }
              else               { '/api/explode' }
      try {
        $null = Invoke-WebRequest -Uri "$base$path" -UseBasicParsing -TimeoutSec 60 -SkipHttpErrorCheck
        $count++
      } catch {
        $errs++
      }
    }
    [pscustomobject]@{ Worker = $workerId; Requests = $count; Errors = $errs }
  } -ArgumentList $baseUrl, $endAt, $w
}

# Live progress every 30s
while ($jobs | Where-Object { $_.State -eq 'Running' }) {
  $remaining = [int](($endAt - (Get-Date)).TotalSeconds)
  if ($remaining -lt 0) { $remaining = 0 }
  Write-Host ("    {0}  workers running, ~{1}s remaining..." -f (Get-Date -Format 'HH:mm:ss'), $remaining) -ForegroundColor DarkGray
  Start-Sleep -Seconds 30
}

Write-Step "Load run complete — collecting worker stats"
$stats = $jobs | ForEach-Object { Receive-Job $_ }
$jobs  | Remove-Job
$stats | Format-Table -AutoSize

$totalReq = ($stats | Measure-Object Requests -Sum).Sum
$totalErr = ($stats | Measure-Object Errors   -Sum).Sum
Write-Info "Total requests : $totalReq"
Write-Info "Total errors   : $totalErr  (expected — /api/explode + sync-over-async pressure)"

# --- Annotate the run in App Insights -----------------------------------------
$annotateScript = Join-Path $PSScriptRoot 'send-release-annotation.ps1'
if (Test-Path $annotateScript) {
  Write-Step "Posting release annotation 'code-optimization-load' to App Insights"
  try {
    & $annotateScript -ResourceGroup $ResourceGroup `
      -Name "code-optimization-load-$(Get-Date -Format 'yyyyMMdd-HHmmss')" `
      -Category 'Deployment' | Out-Null
    Write-Info "Annotation posted."
  } catch {
    Write-Info "Annotation skipped: $($_.Exception.Message)"
  }
}

# --- Follow-up checklist -------------------------------------------------------
Write-Step "What to check in the portal (give Profiler 1-24h to surface insights)"
$appiName = az resource list -g $ResourceGroup --resource-type Microsoft.Insights/components --query "[0].name" -o tsv
Write-Host @"
    1. App Insights -> Investigate -> Performance -> Profiler
         Resource: $appiName
         Wait until a profile session is collected (status = 'Profile available').

    2. App Insights -> Investigate -> Code Optimizations
         Within 1-24h after sustained traffic, you should see one or more of:
           - 'Use StringBuilder instead of concatenation in a loop'
           - 'Excessive exceptions on the hot path'
           - 'Avoid sync-over-async (Task.Result / .Wait())'

    3. KQL sanity check (App Insights logs):
         requests
         | where timestamp > ago(1h)
         | where url endswith '/api/inefficient'
         | summarize count(), avg(duration), p95=percentile(duration, 95)

    4. If after 24h nothing surfaces, drive another run (Code Optimizations
       weighs frequency + duration of samples):
           ./scripts/trigger-code-optimization.ps1 -SkipPublish -DurationMinutes 60
"@ -ForegroundColor Green

Write-Host ""
